kit:
  name: "Cloudera Hadoop"
  link: https://github.com/qubell-bazaar/component-hadoop
  applications:
    - name: "CharacterCount"
      manifest: "https://raw.github.com/qubell-bazaar/component-hadoop/2.7-47p/sample-app.yml"
    - name: "CDH Main"
      manifest: "https://raw.github.com/qubell-bazaar/component-hadoop/2.7-47p/component-hadoop.yml"
    - name: "Cloudera Flume"
      manifest: "https://raw.github.com/qubell-bazaar/component-hadoop/2.7-47p/cloudera-flume.yml"
    - name: "Cloudera Hadoop"
      manifest: "https://raw.github.com/qubell-bazaar/component-hadoop/2.6-47p/cloudera-hadoop.yml"
    - name: "Cloudera Hive"
      manifest: "https://raw.github.com/qubell-bazaar/component-hadoop/2.7-47p/cloudera-hive.yml"
    - name: "Cloudera Hue"
      manifest: "https://raw.github.com/qubell-bazaar/component-hadoop/2.7-47p/cloudera-hue.yml"
    - name: "Cloudera Impala"
      manifest: "https://raw.github.com/qubell-bazaar/component-hadoop/2.7-47p/cloudera-impala.yml"
    - name: "Cloudera Manager"
      manifest: "https://raw.github.com/qubell-bazaar/component-hadoop/2.7-47p/cloudera-manager.yml"
    - name: "Cloudera Oozie"
      manifest: "https://raw.github.com/qubell-bazaar/component-hadoop/2.7-47p/cloudera-oozie.yml"
    - name: "Cloudera Pig"
      manifest: "https://raw.github.com/qubell-bazaar/component-hadoop/2.7-47p/cloudera-pig.yml"
    - name: "Cloudera Solr"
      manifest: "https://raw.github.com/qubell-bazaar/component-hadoop/2.7-47p/cloudera-solr.yml"
    - name: "Cloudera Yarn"
      manifest: "https://raw.github.com/qubell-bazaar/component-hadoop/2.7-47p/cloudera-yarn.yml"
    - name: "Cloudera Spark"
      manifest: "https://raw.github.com/qubell-bazaar/component-hadoop/2.7-47p/cloudera-spark.yml"
    - name: "Cloudera Sqoop"
      manifest: "https://raw.github.com/qubell-bazaar/component-hadoop/2.7-47p/cloudera-sqoop.yml"
  provider:
    name: "Qubell"
    link: http://qubell.com
  documentation:
    overview: |
      This application requires the following items to be configured in your environment:
        * CloudServers account;
        * Ports 7180, 60010, 50030, 50070, 8888 open on the ﬁrewall.
      Please refer to the Getting Started for step-by-step instructions on how to configure your environment.
